library(rpart)
library(caTools)
data<-read.csv("C:/Users/balakrishnan k s/Documents/R programs/drug.csv")
data<-na.omit(data)#remove null
data$Sex<-factor(data$Sex)
data$BP<-factor(data$BP)
data$Cholesterol<-factor(data$Cholesterol)
data$Na_to_K<-as.numeric(data$Na_to_K)
data$Drug<-factor(data$Drug)
sample <- sample.split(data$Drug, SplitRatio = 0.7)
train <- subset(data, sample == TRUE)
test <- subset(data, sample == FALSE)
tree_model <- rpart(Drug ~ .,train, method = "class")
plot(tree_model)
text(tree_model)
predictions <- predict(tree_model,test, type = "class")
accuracy <- mean(predictions == test$Drug)
cat("Accuracy:",accuracy)